cc_binary(
    name = "part1",
    srcs = ["part1.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:io",
        "@fmt",
    ],
)

cc_binary(
    name = "part2",
    srcs = ["part2.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:io",
        "@fmt",
    ],
)
